import random

problems = [
    ("Valid Anagram", 1),
    ("Contains Duplicate", 1),
    ("Group Anagrams", 1),
    ("Top K Frequent Elements", 1),
    ("Ransom Note", 1),
    ("Two Sum", 1),
    ("Two Sum II", 1),
    ("3Sum", 1),
    ("Subarray Sum Equals K", 1),
    ("Continuous Subarray Sum", 1),
    ("Linked List Cycle", 1),
    ("Remove Duplicates from Sorted Array", 1),
    ("4Sum", 1),
    ("Linked List Cycle II", 1),
    ("Remove Duplicates (II)", 1),
    ("Container With Most Water", 1),
    ("Happy Number", 1),
    ("Remove Element", 1),
    ("Trapping Rain Water", 1),
    ("Find the Duplicate Number", 1),
    ("Merge Sorted Array", 1),
    ("Valid Palindrome", 1),
    ("Middle of Linked List (ADD)", 1),
    ("Sort Colors", 1),
    ("Valid Palindrome II", 1),
    ("Palindrome Linked List", 1),
    ("Move Zeroes", 1),
    ("Sum of Square Numbers", 1),
    ("Two Sum IV", 1),
    ("Partition List", 1),
    ("Remove Duplicates (Linked List I, II)", 1),
    ("3Sum Smaller", 1),
    ("String Compression", 1),
    ("K-diff Pairs", 1),
    ("Reverse String (I, II)", 1),
    ("Intersection of Two Linked Lists", 1),
    ("Reverse Vowels", 1),
    ("Maximum Average Subarray I", 1),
    ("Permutation in String", 1),
    ("Longest Substring Without Repeating Characters", 1),
    ("Longest Repeating Character Replacement", 1),
    ("Fruit Into Baskets", 1),
    ("Longest Substring with At Most K Distinct Characters", 1),
    ("Minimum Size Subarray Sum", 1),
    ("Find All Anagrams in a String", 1),
    ("Valid Parentheses", 1),
    ("Min Stack", 1),
    ("Baseball Game", 1),
    ("Simplify Path", 1),
    ("Longest Valid Parentheses", 1),
    ("Daily Temperatures", 1),
    ("Next Greater Element I ", 1),
    ("Online Stock Span", 1),
    ("Remove K Digits", 1),
    ("Asteroid Collision", 1),
    ("Validate Stack Sequences", 1),
    ("Decode String", 1),
    ("Evaluate Reverse Polish Notation", 1),
    ("Basic Calculator II", 1),
    ("Binary Search", 1),
    ("Search Insert Position", 1),
    ("Search a 2D Matrix", 1),
    ("Find First and Last Position of Element in Sorted Array", 1),
    ("Find K Closest Elements ", 1),
    ("Find Right Interval", 1),
    ("Search in Rotated Sorted Array", 1),
    ("Find Minimum in Rotated Sorted Array", 1),
    ("Sqrt(x) ", 1),
    ("First Bad Version", 1),
    ("Valid Perfect Square", 1),
    ("Same Tree", 1),
    ("Invert Binary Tree", 1),
    ("Maximum Depth of Binary Tree ", 1),
    ("Balanced Binary Tree", 1),
    ("Diameter of Binary Tree", 1),
    ("Symmetric Tree", 1),
    ("Path Sum", 1),
    ("Path Sum II", 1),
    ("Binary Tree Level Order Traversal", 1),
    ("Binary Tree Right Side View", 1),
    ("Minimum Depth of Binary Tree", 1),
    ("Validate Binary Search Tree", 1),
    ("Kth Smallest Element in a BST", 1),
    ("Lowest Common Ancestor of a BST", 1),
    ("Lowest Common Ancestor of a Binary Tree", 1),
    ("House Robber III", 1),
    ("Number of Islands", 1),
    ("Clone Graph", 1),
    ("Rotting Oranges", 1),
    ("Graph Valid Tree", 1),
    ("Course Schedule", 1),
    ("Number of Provinces", 1),
    ("Climbing Stairs", 1),
    ("House Robber", 1),
    ("Unique Paths", 1),
    ("Minimum Path Sum", 0),
    ("Edit Distance", 1),
    ("Coin Change", 1),
    ("Longest Increasing Subsequence", 1),
]

n = 3
review_counter = 0
print("problems count: ", len(problems))
problems = [p for p in problems if p[1] == 0]
print("remaining problems: ", len(problems))
if not problems:
    print(
        "All problems is reviewed reset to start fresh and don't forget to increment the review counter"
    )
    exit()

numbers = random.sample(range(0, len(problems)), n)
numbers.sort()
for num in numbers:
    print(problems[num][0])
